name: Build Native

on:
  pull_request:
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/build-native-matrix.yml
    permissions:
      contents: read
